name: todoadvancelevel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  date_picker_plus: ^4.1.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
